spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:h2:tcp://localhost/~/test
          username: sa
          password: ""
          driver-class-name: org.h2.Driver
          schema: db/schema.sql
        slave_1:
          url: jdbc:h2:tcp://localhost/~/test
          username: sa
          password: ""
          driver-class-name: org.h2.Driver
        slave_2:
          url: jdbc:h2:tcp://localhost/~/test
          username: sa
          password: ""
          driver-class-name: org.h2.Driver
        slave_3:
          url: jdbc:h2:tcp://localhost/~/test
          username: sa
          password: ""
          driver-class-name: org.h2.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
    jmx-enabled: true
  resources:
    static-locations: classpath:/static,classpath:/resources/
logging:
  level:
    com.baomidou: debug